#!/usr/bin/env node
import assert from "node:assert/strict";

import { evaluateMinesweeperRules } from "../runtime/financial-minesweeper/minesweeper-rules.js";

const evaluation = evaluateMinesweeperRules({
  code: "600000",
  anchorYear: 2024,
  companyName: "测试公司",
  industry: "化工材料",
  snapshots: [
    {
      code: "600000",
      period: "2024",
      auditResult: "标准无保留意见",
      revenue: 1000,
      netProfit: 80,
      operatingCashFlow: 120,
      capitalExpenditure: -90,
      totalAssets: 3000,
      totalLiabilities: 1800,
      interestBearingDebt: 600,
      cashAndEquivalents: 700,
      accountsReceivable: 260,
    },
    {
      code: "600000",
      period: "2023",
      revenue: 900,
      netProfit: 90,
      operatingCashFlow: 60,
      capitalExpenditure: -50,
      totalAssets: 1800,
      totalLiabilities: 1100,
      interestBearingDebt: 500,
      cashAndEquivalents: 300,
      accountsReceivable: 180,
    },
    {
      code: "600000",
      period: "2022",
      revenue: 800,
      netProfit: 70,
      operatingCashFlow: 50,
      capitalExpenditure: -30,
      totalAssets: 1200,
      totalLiabilities: 700,
      accountsReceivable: 120,
    },
  ],
  trends: [
    {
      year: "2024",
      grossMarginPct: 35,
      revenue: 1000,
      netProfit: 80,
      accountsReceivable: 260,
      accountsPayable: 160,
      inventoryDays: 120,
      impairmentLoss: 20,
      operatingCashFlow: 120,
      freeCashFlow: 30,
      ocfToNetProfit: 1.5,
      salesExpenseRatioPct: 6,
      adminExpenseRatioPct: 5,
      financialExpenseRatioPct: 2,
      reportDate: "2024-12-31",
      source: "test",
      warnings: [],
    },
    {
      year: "2023",
      grossMarginPct: 30,
      revenue: 900,
      netProfit: 90,
      accountsReceivable: 180,
      accountsPayable: 200,
      inventoryDays: 90,
      impairmentLoss: 8,
      operatingCashFlow: 60,
      freeCashFlow: 10,
      ocfToNetProfit: 0.66,
      salesExpenseRatioPct: 8,
      adminExpenseRatioPct: 7,
      financialExpenseRatioPct: 3,
      reportDate: "2023-12-31",
      source: "test",
      warnings: [],
    },
    {
      year: "2022",
      grossMarginPct: 29,
      revenue: 800,
      netProfit: 70,
      accountsReceivable: 120,
      accountsPayable: 220,
      inventoryDays: 75,
      impairmentLoss: 6,
      operatingCashFlow: 50,
      freeCashFlow: 20,
      ocfToNetProfit: 0.71,
      salesExpenseRatioPct: 8,
      adminExpenseRatioPct: 8,
      financialExpenseRatioPct: 3,
      reportDate: "2022-12-31",
      source: "test",
      warnings: [],
    },
  ],
  governanceEvents: [],
  latestBalance: {
    goodwill: 180,
    total_hldr_eqy_exc_min_int: 300,
    oth_receiv: 120,
    total_assets: 3000,
  },
  annualMetaByYear: {
    "2024": {
      year: "2024",
      reportDate: "2024-12-31",
      annDate: "20250420",
      auditAgency: "中审会计师事务所",
      topHolderRatio: 48,
    },
    "2023": {
      year: "2023",
      reportDate: "2023-12-31",
      annDate: "20240420",
      auditAgency: "中审会计师事务所",
      topHolderRatio: 50,
    },
    "2022": {
      year: "2022",
      reportDate: "2022-12-31",
      annDate: "20230415",
      auditAgency: "立信会计师事务所",
      topHolderRatio: 52,
    },
  },
  incomeByYear: {
    "2024": {
      revenue: 1000,
      oth_biz_income: 90,
      oper_cost: 650,
      sell_exp: 60,
      admin_exp: 50,
      fin_exp: 30,
      n_income_attr_p: 80,
      credit_impa_loss: 10,
      rd_capitalized: 40,
      rd_expensed: 60,
    },
    "2023": {
      revenue: 900,
      oth_biz_income: 20,
      oper_cost: 600,
      sell_exp: 70,
      admin_exp: 60,
      fin_exp: 35,
      n_income_attr_p: 90,
      credit_impa_loss: 6,
    },
    "2022": {
      revenue: 800,
      oth_biz_income: 18,
      oper_cost: 530,
      sell_exp: 64,
      admin_exp: 60,
      fin_exp: 32,
      n_income_attr_p: 70,
      credit_impa_loss: 5,
    },
  },
  balanceByYear: {
    "2024": {
      reportDate: "2024-12-31",
      cip: 200,
      fixed_assets: 1000,
      long_term_deferred_expenses: 80,
      accounts_receiv: 260,
      ann_date: "20250420",
    },
    "2023": {
      reportDate: "2023-12-31",
      cip: 120,
      fixed_assets: 980,
      long_term_deferred_expenses: 30,
      accounts_receiv: 180,
      ann_date: "20240420",
    },
    "2022": {
      reportDate: "2022-12-31",
      cip: 80,
      fixed_assets: 960,
      long_term_deferred_expenses: 20,
      accounts_receiv: 120,
      ann_date: "20230415",
    },
  },
  cashflowByYear: {
    "2024": {
      c_recp_prov_sg_act: 1050,
    },
  },
  dataPackReportMarkdown: [
    "## MDA 管理层讨论与分析",
    "财务总监发生变更，独立董事有辞职情况。公司拟并购进入新业务与主营无关。",
    "## OPERATING 经营指标",
    "运输费下降明显，同时营收增长。资本化率 42%。",
    "## SEGMENT 分部收入",
    "前五大客户占比 55%，客户集中度较高。",
    "## P3 应收账款账龄",
    "账龄与坏账准备有披露。",
  ].join("\n"),
  dataPackReportSections: {
    MDA: "财务总监变更，独立董事辞职。拟跨界并购进入新业务。",
    OPERATING: "运输费下降明显，营收增长；资本化率 42%。",
    SEGMENT: "前五大客户占比 55%。",
    P3: "账龄结构与坏账准备。",
  },
  pdfQuality: {
    gateVerdict: "DEGRADED",
    missingCritical: [],
    lowConfidenceCritical: ["P13"],
    sectionsFound: 8,
    sectionsTotal: 12,
    criticalSectionIds: ["P2", "P3", "P4", "P6", "P13", "MDA"],
    allowsFinalNarrativeComplete: true,
    humanReviewPriority: ["P13"],
  },
});

const mustBeEvaluated = [
  "0.2",
  "1.3",
  "1.4",
  "3.3",
  "3.4",
  "3.5",
  "4.2",
  "4.4",
  "5.1",
  "5.2",
  "5.3",
  "5.4",
  "5.5",
  "5.6",
  "6.2",
];

for (const id of mustBeEvaluated) {
  const row = evaluation.rows.find((r) => r.id === id);
  assert.ok(row, `missing rule row: ${id}`);
  assert.notEqual(row?.verdict, "SKIP", `rule ${id} should be evaluated when full context exists`);
}

console.log("[test:financial-minesweeper-rules] ok");
